package angelitogui_netbeans;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 * Este formulario tiene como objetivo otorgar o denegar acceso al sistema
 * unicamente al personal autorizado
 * 
 * @author jonce
 */
public class LogIn extends javax.swing.JFrame {   
    
    public static final String URL="jdbc:mysql://localhost/angelito";
    public static final String USERNAME="root";
    public static final String PASSWORD="coatza";
    PreparedStatement ps;
    ResultSet rs;
    
            
    public LogIn() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblUsuarioLogin.setVisible(false);
        
    }
    
    String usuarioActual;
    
    //Método para validar Credenciales
    public void validarAdmin(){
    int resultado = 0;
    Connection con = Conexion.getConexion();
        try {
            String usuario=txtUsuario.getText();
            String contraseña=String.valueOf(txtPassword.getPassword());
            String sql="SELECT * FROM usuario WHERE usuario='"+usuario+"' and"
                    + " contraseña='"+contraseña+"';";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            if (rs.next()) {
                resultado=1;
                if (resultado==1) {
                    lblUsuarioLogin.setText(txtUsuario.getText());
                    MenuPrincipal principal = new MenuPrincipal();
                    principal.setVisible(true);
                    principal.lblUsuarioMenu.setText(lblUsuarioLogin.getText());
                    this.dispose();
                }
            }else{
            JOptionPane.showMessageDialog(null, "Datos Incorrectos");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al conectar con la"
                    + " base de datos");
        }
                    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelIniciodeSesion = new javax.swing.JLabel();
        jLabelAngelito = new javax.swing.JLabel();
        jLabelRegalosIMGbd = new javax.swing.JLabel();
        jSeparatorUsuario = new javax.swing.JSeparator();
        jLabelTitulo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jSeparatorContraseña = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        BotonEntrar = new javax.swing.JPanel();
        LabelEntrar = new javax.swing.JLabel();
        lblUsuarioLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabelIniciodeSesion.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabelIniciodeSesion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIniciodeSesion.setText("Inicio de Sesión");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(jLabelIniciodeSesion)
                .addGap(176, 176, 176))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabelIniciodeSesion)
                .addGap(26, 26, 26))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 620, 100));

        jLabelAngelito.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAngelito.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabelAngelito.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAngelito.setText("Angelito");
        bg.add(jLabelAngelito, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        jLabelRegalosIMGbd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/green-background-with-gift-boxes-new-year-background-free-vector.jpg"))); // NOI18N
        jLabelRegalosIMGbd.setText("jLabel2");
        bg.add(jLabelRegalosIMGbd, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 400, 810));
        bg.add(jSeparatorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 410, 10));

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setText("Tienda  De Regalos");
        bg.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Roboto", 2, 20)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("Ingrese su nombre de usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        bg.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 400, 50));

        jLabelUsuario.setFont(new java.awt.Font("Roboto", 3, 27)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUsuario.setText("Usuario");
        bg.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        jLabelContraseña.setFont(new java.awt.Font("Roboto", 3, 27)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(0, 0, 0));
        jLabelContraseña.setText("Contraseña");
        bg.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, -1));
        bg.add(jSeparatorContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, 410, 20));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(204, 204, 204));
        txtPassword.setText("jPasswordField1");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPasswordMousePressed(evt);
            }
        });
        bg.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 370, -1));

        BotonEntrar.setBackground(new java.awt.Color(42, 92, 44));
        BotonEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEntrarMouseClicked(evt);
            }
        });

        LabelEntrar.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        LabelEntrar.setForeground(new java.awt.Color(255, 255, 255));
        LabelEntrar.setText("Entrar");

        javax.swing.GroupLayout BotonEntrarLayout = new javax.swing.GroupLayout(BotonEntrar);
        BotonEntrar.setLayout(BotonEntrarLayout);
        BotonEntrarLayout.setHorizontalGroup(
            BotonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonEntrarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(LabelEntrar)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        BotonEntrarLayout.setVerticalGroup(
            BotonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonEntrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelEntrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(BotonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 690, 140, 40));

        lblUsuarioLogin.setText("jLabel1");
        lblUsuarioLogin.setEnabled(false);
        bg.add(lblUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 790, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        txtUsuario.setText("");
        txtUsuario.setForeground(Color.BLACK);
               
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMousePressed
        txtPassword.setForeground(Color.BLACK);
        txtPassword.setText("");
                
    }//GEN-LAST:event_txtPasswordMousePressed

    private void BotonEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEntrarMouseClicked
        
        lblUsuarioLogin.setText(txtUsuario.getText());
        usuarioActual = lblUsuarioLogin.getText();
        
        validarAdmin();
        MenuPrincipal mp = new MenuPrincipal();
        mp.lblUsuarioMenu.setText(lblUsuarioLogin.getText());
        
    }//GEN-LAST:event_BotonEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonEntrar;
    private javax.swing.JLabel LabelEntrar;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabelAngelito;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelIniciodeSesion;
    private javax.swing.JLabel jLabelRegalosIMGbd;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparatorContraseña;
    private javax.swing.JSeparator jSeparatorUsuario;
    private javax.swing.JLabel lblUsuarioLogin;
    private javax.swing.JPasswordField txtPassword;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

   
}
