package angelitogui_netbeans;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import angelitogui_netbeans.Conexion;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 * Este formulario es correspondiente al menú principal, aquí el
 * usuario logrará ser redireccionado a la interfaz correspondiente
 * a la acción que desea realizar dentro del sistema.
 * 
 * @author jonce
 */

public class MenuPrincipal extends javax.swing.JFrame {
        
    boolean booVentas;
           
    public MenuPrincipal() {
        initComponents();
        lblUsuarioMenu.setVisible(false);
        lblNventa.setVisible(false);
        
        this.setLocationRelativeTo(null);
        
        if (booVentas==true) {
            listVentas.setVisible(true);
            
        }else {
            listVentas.setVisible(false);
        
        }
        
                
    }
    
    
    //Método para identificar el numero de ventas que se han realizado
    private void numVenta(){
    
        Connection con = Conexion.getConexion();
        Statement stmt;
        ResultSet rs = null;
                    
        try {
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT COUNT(*) as ventasRealizadas "
                    + "FROM `venta`");
            
            if (rs.next()) {
                
                int nVenta = Integer.parseInt(rs.getString("ventasRealizadas"));
                nVenta++;
                lblNventa.setText(Integer.toString(nVenta));
                RegistrarVenta registrarV = new RegistrarVenta();
                registrarV.lblNumerodeVenta.setText(lblNventa.getText());
                
            }else
                JOptionPane.showMessageDialog(null, "error");
            
        } catch (SQLException e) {
            System.err.println(e);
            
        }
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        btProducto = new javax.swing.JButton();
        btProveedor = new javax.swing.JButton();
        btCompras = new javax.swing.JButton();
        btInventario = new javax.swing.JButton();
        btUsuarios = new javax.swing.JButton();
        btVentas = new javax.swing.JButton();
        btHistorial = new javax.swing.JLabel();
        btAyuda = new javax.swing.JLabel();
        btRespaldo = new javax.swing.JLabel();
        lbManual = new javax.swing.JLabel();
        lbManual1 = new javax.swing.JLabel();
        lbManual2 = new javax.swing.JLabel();
        listVentas = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        lblUsuarioMenu = new javax.swing.JLabel();
        lblNventa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(77, 160, 80));
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(77, 160, 80));

        labelTitulo.setFont(new java.awt.Font("Times New Roman", 3, 52)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Tienda de Regalos \"Angelito\"");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addGap(187, 187, 187))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addGap(31, 31, 31))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblMenu.setFont(new java.awt.Font("Roboto", 1, 41)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(0, 0, 0));
        lblMenu.setText("Menú Principal");
        bg.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 150, -1, -1));

        btProducto.setBackground(new java.awt.Color(77, 160, 80));
        btProducto.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        btProducto.setForeground(new java.awt.Color(255, 255, 255));
        btProducto.setText("Productos");
        btProducto.setBorder(null);
        btProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProductoActionPerformed(evt);
            }
        });
        bg.add(btProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 286, 118, 50));

        btProveedor.setBackground(new java.awt.Color(77, 160, 80));
        btProveedor.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        btProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btProveedor.setText("Proveedores");
        btProveedor.setBorder(null);
        btProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProveedorActionPerformed(evt);
            }
        });
        bg.add(btProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 286, 118, 50));

        btCompras.setBackground(new java.awt.Color(77, 160, 80));
        btCompras.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        btCompras.setForeground(new java.awt.Color(255, 255, 255));
        btCompras.setText("Compras");
        btCompras.setBorder(null);
        btCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprasActionPerformed(evt);
            }
        });
        bg.add(btCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 286, 118, 50));

        btInventario.setBackground(new java.awt.Color(77, 160, 80));
        btInventario.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        btInventario.setForeground(new java.awt.Color(255, 255, 255));
        btInventario.setText("Inventario");
        btInventario.setBorder(null);
        btInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInventarioActionPerformed(evt);
            }
        });
        bg.add(btInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 450, 118, 50));

        btUsuarios.setBackground(new java.awt.Color(77, 160, 80));
        btUsuarios.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        btUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btUsuarios.setText("Usuarios");
        btUsuarios.setBorder(null);
        btUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuariosActionPerformed(evt);
            }
        });
        bg.add(btUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 450, 118, 50));

        btVentas.setBackground(new java.awt.Color(77, 160, 80));
        btVentas.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        btVentas.setForeground(new java.awt.Color(255, 255, 255));
        btVentas.setText("Ventas");
        btVentas.setBorder(null);
        btVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVentasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btVentasMousePressed(evt);
            }
        });
        btVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVentasActionPerformed(evt);
            }
        });
        bg.add(btVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 450, 118, 50));

        btHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/clock_23808.png"))); // NOI18N
        btHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(btHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 614, -1, -1));

        btAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/1458264589_question_quiz_feedback_comments_enquiry_help_support_icon-icons.com_55335.png"))); // NOI18N
        btAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(btAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 612, 99, -1));

        btRespaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/cloud-circle_117144.png"))); // NOI18N
        btRespaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(btRespaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 612, -1, -1));

        lbManual.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbManual.setForeground(new java.awt.Color(0, 0, 0));
        lbManual.setText("Historial de Cambios");
        bg.add(lbManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 708, -1, -1));

        lbManual1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lbManual1.setForeground(new java.awt.Color(0, 0, 0));
        lbManual1.setText("Respaldo");
        bg.add(lbManual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 706, -1, -1));

        lbManual2.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lbManual2.setForeground(new java.awt.Color(0, 0, 0));
        lbManual2.setText("Manual");
        bg.add(lbManual2, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 706, -1, -1));

        jList1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Buscar", "Registrar Venta", "Lista de Ventas" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList1MousePressed(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        listVentas.setViewportView(jList1);

        bg.add(listVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 506, 118, 79));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 1080, 10));

        lblUsuarioMenu.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarioMenu.setText("jLabel1");
        lblUsuarioMenu.setEnabled(false);
        bg.add(lblUsuarioMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, -1, -1));

        lblNventa.setText("jLabel1");
        bg.add(lblNventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 730, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btProductoActionPerformed

    private void btProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btProveedorActionPerformed

    private void btComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btComprasActionPerformed

    private void btInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btInventarioActionPerformed

    private void btUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btUsuariosActionPerformed

    private void btVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVentasActionPerformed
        booVentas = true;
              
    }//GEN-LAST:event_btVentasActionPerformed

    private void btVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVentasMouseClicked
        booVentas = true;  
        
    }//GEN-LAST:event_btVentasMouseClicked

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged

    }//GEN-LAST:event_jList1ValueChanged

    private void btVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVentasMousePressed
        booVentas = true;
        numVenta();
        this.listVentas.setVisible(true);
     
    }//GEN-LAST:event_btVentasMousePressed

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        this.listVentas.setVisible(false);
        
    }//GEN-LAST:event_bgMousePressed

    private void jList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MousePressed
        RegistrarVenta registrarV = new RegistrarVenta();
            registrarV.setVisible(true);
            registrarV.lblNumerodeVenta.setText(lblNventa.getText());
            registrarV.lblUsuarioActual.setText(lblUsuarioMenu.getText());
            
        this.dispose();
        
    }//GEN-LAST:event_jList1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btAyuda;
    private javax.swing.JButton btCompras;
    private javax.swing.JLabel btHistorial;
    private javax.swing.JButton btInventario;
    private javax.swing.JButton btProducto;
    private javax.swing.JButton btProveedor;
    private javax.swing.JLabel btRespaldo;
    private javax.swing.JButton btUsuarios;
    private javax.swing.JButton btVentas;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel lbManual;
    private javax.swing.JLabel lbManual1;
    private javax.swing.JLabel lbManual2;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblNventa;
    public static javax.swing.JLabel lblUsuarioMenu;
    private javax.swing.JScrollPane listVentas;
    // End of variables declaration//GEN-END:variables
}
